/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.demo;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import objects.User;
import socket.SocketMessageHandle;
import static view.demo.Program.client;
import static view.demo.PnlLogin.txtPassword_login;
import static view.demo.PnlLogin.txtUsername_login;


public class PnlRegister extends javax.swing.JPanel {

    /**
     * Creates new form pnlRegister
     */
    JFileChooser fc = new JFileChooser();
    byte[] imageArray;
    
    public void customTextField(){
        TextPrompt tpFirstName = new TextPrompt("Full name", txtFullName);
        TextPrompt tpUser = new TextPrompt("Username", txtUser);
        TextPrompt tpPass = new TextPrompt("Password", txtPass);
        TextPrompt tpRepeat = new TextPrompt("Repeat password", txtRepeat);
        TextPrompt tpCountry = new TextPrompt("Country", txtCountry);
        tpFirstName.setForeground(new Color(204,204,204));
        tpUser.setForeground(new Color(204,204,204));
        tpPass.setForeground(new Color(204,204,204));
        tpRepeat.setForeground(new Color(204,204,204));
        tpCountry.setForeground(new Color(204,204,204));
    }
    
    public PnlRegister() {
        initComponents();
        try {
            imageArray = Files.readAllBytes((new File("./src/view/Images/Use-icon.png")).toPath());
        } catch (IOException ex) {
            Logger.getLogger(PnlRegister.class.getName()).log(Level.SEVERE, null, ex);
        }
        lblBack.setCursor(new Cursor(Cursor.HAND_CURSOR));
        customTextField();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtFullName = new javax.swing.JTextField();
        txtUser = new javax.swing.JTextField();
        txtCountry = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        lblBack = new javax.swing.JLabel();
        txtRepeat = new javax.swing.JPasswordField();
        lblAvartar = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        genderMale = new javax.swing.JRadioButton();
        genderFemale = new javax.swing.JRadioButton();

        setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Create.png"))); // NOI18N

        txtFullName.setBackground(new Color(0,0,0,0));
        txtFullName.setForeground(new java.awt.Color(255, 255, 255));
        txtFullName.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txtUser.setBackground(new Color(0,0,0,0));
        txtUser.setForeground(new java.awt.Color(255, 255, 255));
        txtUser.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txtCountry.setBackground(new Color(0,0,0,0));
        txtCountry.setForeground(new java.awt.Color(255, 255, 255));
        txtCountry.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        txtPass.setBackground(new Color(0,0,0,0));
        txtPass.setForeground(new java.awt.Color(255, 255, 255));
        txtPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Register.png"))); // NOI18N
        btnRegister.setText("Create");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        lblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Back.png"))); // NOI18N
        lblBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBackMouseClicked(evt);
            }
        });

        txtRepeat.setBackground(new Color(0,0,0,0));
        txtRepeat.setForeground(new java.awt.Color(255, 255, 255));
        txtRepeat.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));

        lblAvartar.setBackground(new java.awt.Color(255, 255, 255));
        lblAvartar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/Images/Use-icon.png"))); // NOI18N
        lblAvartar.setOpaque(true);

        btnUpload.setText("UpLoad");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });

        buttonGroup1.add(genderMale);
        genderMale.setForeground(new java.awt.Color(255, 255, 255));
        genderMale.setSelected(true);
        genderMale.setText("Nam");

        buttonGroup1.add(genderFemale);
        genderFemale.setForeground(new java.awt.Color(255, 255, 255));
        genderFemale.setText("Nữ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(lblAvartar)
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(genderMale)
                        .addGap(18, 18, 18)
                        .addComponent(genderFemale))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnUpload)
                        .addGap(98, 98, 98)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(580, 580, 580)
                        .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblAvartar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(genderMale))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(genderFemale)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(btnUpload))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtRepeat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(txtCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(lblBack, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void RegisterDatabase(){

    }
    
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        if( (!txtUser.getText().equals("")) && (!String.valueOf(txtPass.getPassword()).equals("")) && (String.valueOf(txtPass.getPassword()).equals(String.valueOf(txtRepeat.getPassword())))){
            boolean gender = (genderMale.isSelected() ? true : false);
            User newUser = new User(txtUser.getText(),txtFullName.getText(),String.valueOf(txtPass.getPassword()),gender);
            
            client.declareHandle("registerRS",  new SocketMessageHandle(){
                @Override
                public void Handle(Object... params) {
                    if((boolean)params[0] == false){
                        JOptionPane.showMessageDialog(null, "Username đã tồn tại !!! \n Vui lòng chọn username khác");
                    }
                    else
                    {
                        User newuser = (User) params[1];
                        byte[] img = (byte[]) params[2];
                        


                        txtCountry.setText("");
                        txtFullName.setText("");
                        txtPass.setText("");
                        txtRepeat.setText("");
                        txtUser.setText("");
                        RegisterDatabase();
                        Program.p3.setVisible(false);
                        Program.p1.setVisible(true);


                    }
                }
            });
            
            try {
                client.sendMessage("register",newUser,imageArray);
            } catch (IOException ex) {
                Logger.getLogger(PnlRegister.class.getName()).log(Level.SEVERE, null, ex);
            }
                
        }
        else{
            if(!txtPass.getPassword().equals(txtRepeat)){
                JOptionPane.showMessageDialog(null,"Password không đồng nhất !!!\n Vui lòng kiểm tra lại.");
            }
            else{
                JOptionPane.showMessageDialog(null,"Thông tin đăng nhập chưa đầy đủ");
            }
        }
        lblAvartar.setIcon(new ImageIcon("src/view/Images/Use-icon.png"));
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void lblBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        Program.p1.setVisible(true);
        
    }//GEN-LAST:event_lblBackMouseClicked

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        JFileChooser fc = new JFileChooser();
        fc.setCurrentDirectory(new File("D:/"));
        fc.setDialogTitle("Upload Image");
        
        int choose = -1;
        JPanel p = new JPanel();
        p.add(fc);
        choose = fc.showOpenDialog(p);
        String pathImage;
        if(choose == JFileChooser.APPROVE_OPTION)
        {
            try {
                File selectedFile = fc.getSelectedFile();
                if(selectedFile != null){
                    imageArray = Files.readAllBytes(selectedFile.toPath());
                    System.out.println(imageArray);
                }
                pathImage = selectedFile.getPath();
                BufferedImage image = null;
                
                image = ImageIO.read(new File(pathImage));
                ImageIcon icon = new ImageIcon(image.getScaledInstance(lblAvartar.getWidth(),lblAvartar.getHeight(),image.SCALE_SMOOTH));
                lblAvartar.setIcon(icon);
            } catch (IOException ex) {
                Logger.getLogger(PnlRegister.class.getName()).log(Level.SEVERE, null, ex);
            }
        }   
    }//GEN-LAST:event_btnUploadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpload;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton genderFemale;
    private javax.swing.JRadioButton genderMale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAvartar;
    private javax.swing.JLabel lblBack;
    private javax.swing.JTextField txtCountry;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtRepeat;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
