/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.demo;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.GroupLayout;
import javax.swing.JFrame;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import objects.FriendRequest;
import objects.User;
import socket.Client;
import sun.net.www.protocol.mailto.MailToURLConnection;

public class Program extends javax.swing.JFrame {

    /**
     * Creates new form Program
     */
    static User currentUser = null;
    static byte[] currentAvatar = null;
    static List<User> currentFriends;
    static PnlLogin p1;
    static PnlMain p2;
    static PnlRegister p3;
    static GridBagConstraints gridBag;
    static JMenuItem itemSignout = new JMenuItem(" Sign out");
    static Client client;
    static List<FriendRequest> friendRequests;

    public Program() throws IOException {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setPreferredSize(new Dimension(700,500));
        this.setMaximumSize(new Dimension(700,500));
        this.setMinimumSize(new Dimension(700,500));
        p1 = new PnlLogin();
        p3 = new PnlRegister();
        gridBag = new GridBagConstraints();

        gridBag.gridx = 0;
        gridBag.gridy = 0;
        pnlDynamic.setLayout(new GridBagLayout());
        pnlDynamic.add(p1, gridBag);
        pnlDynamic.add(p3, gridBag);

        p1.setVisible(true);
        p3.setVisible(false);

        client = new Client();
        client.start();

        itemSignout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    client.sendMessage("SignOut", currentUser);
                } catch (IOException ex) {
                    Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
                }
                PnlLogin.txtPassword_login.setText("");
                PnlLogin.txtUsername_login.setText("");
                Program.this.pnlDynamic.remove(p2);
                Program.this.currentUser = null;
                Program.this.currentAvatar = null;
                Program.this.currentFriends = null;
                p1.setVisible(true);
                menuHome.remove(itemSignout);
            }
        });
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        itemClose = new javax.swing.JMenuItem();
        menuHelp = new javax.swing.JMenu();
        itemHelp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setLocation(new java.awt.Point(0, 0));
        setMaximumSize(new java.awt.Dimension(700, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        pnlDynamic.setBackground(new java.awt.Color(102, 102, 102));
        pnlDynamic.setLayout(new java.awt.BorderLayout());

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setMaximumSize(new java.awt.Dimension(60, 32769));

        menuHome.setText("Home");

        itemClose.setText("Close");
        itemClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCloseActionPerformed(evt);
            }
        });
        menuHome.add(itemClose);

        jMenuBar1.add(menuHome);

        menuHelp.setText("Help");

        itemHelp.setText("About");
        menuHelp.add(itemHelp);

        jMenuBar1.add(menuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addComponent(pnlDynamic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(641, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlDynamic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 452, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemCloseActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        try {
            if(client.os!=null)
            client.sendMessage("SignOut", currentUser);
        } catch (IOException ex) {
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line argumentsDuyen
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>aa
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>Duyen
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Program().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Program.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemClose;
    private javax.swing.JMenuItem itemHelp;
    public javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuHelp;
    public static final javax.swing.JMenu menuHome = new javax.swing.JMenu();
    public static final javax.swing.JPanel pnlDynamic = new javax.swing.JPanel();
    // End of variables declaration//GEN-END:variables
}
